#!/usr/bin/env bash
#a Bash script that displays the PID, along with the process name
script_pid=$$
process_list=$(pgrep -af bash | grep -v "grep")
echo "$process_list" | while read -r line; do
  pid=$(echo "$line" | awk '{print $1}')
  process_name=$(echo "$line" | awk '{print $0}')
  echo "$pid $process_name"
done

echo "$script_pid $0"
